# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "contests", :force => true do |t|
    t.column "title", :string, :limit => 200, :default => "", :null => false
    t.column "description", :text
    t.column "start_date", :datetime
    t.column "end_date", :datetime
    t.column "is_visible", :integer, :limit => 1
    t.column "max_user_pictures", :integer, :limit => 4
    t.column "max_user_votes", :integer, :limit => 4
  end

  add_index "contests", ["title"], :name => "contests_title_index", :unique => true

  create_table "pictures", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "contest_id", :integer
    t.column "name", :string, :limit => 200, :default => "", :null => false
    t.column "format", :string, :limit => 5, :default => "", :null => false
    t.column "comment", :string, :limit => 512
  end

  add_index "pictures", ["name", "user_id"], :name => "pictures_name_index", :unique => true
  add_index "pictures", ["user_id"], :name => "fk_picture_user"
  add_index "pictures", ["contest_id"], :name => "fk_picture_contest"

  create_table "user_ratings", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "picture_id", :integer, :default => 0, :null => false
    t.column "rating", :integer, :limit => 4
  end

  add_index "user_ratings", ["user_id"], :name => "fk_user_rating_user"
  add_index "user_ratings", ["picture_id"], :name => "fk_user_rating_picture"

  create_table "users", :force => true do |t|
    t.column "loginame", :string, :limit => 50, :default => "", :null => false
    t.column "password", :string, :limit => 50, :default => "", :null => false
    t.column "email", :string, :limit => 100, :default => "", :null => false
    t.column "is_admin", :integer, :limit => 1, :default => 0, :null => false
    t.column "register_date", :datetime, :null => false
    t.column "first_name", :string, :limit => 100
    t.column "last_name", :string, :limit => 100
    t.column "person_activity", :string, :limit => 100
    t.column "spam", :integer, :limit => 1, :default => 1, :null => false
    t.column "password_salt", :string
  end

end
